name: Web
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: setup just
        uses: extractions/setup-just@v3
      - name: install
        run: just web/install
      - name: build
        run: just web/build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: setup just
        uses: extractions/setup-just@v3
      - name: install
        run: just web/install
      - name: lint
        run: just web/lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: setup just
        uses: extractions/setup-just@v3
      - name: install
        run: just web/install
      - name: typecheck
        run: just web/typecheck
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: setup just
        uses: extractions/setup-just@v3
      - name: install
        run: just web/install
      - name: fmt-check
        run: just web/fmt-check
